package main

import (
	"database/sql"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	_ "modernc.org/sqlite"

	"github.com/gongahkia/tanabata/api/internal/catalog"
)

type column struct {
	name     string
	typeName string
	nullable bool
	primary  bool
}

type foreignKey struct {
	table  string
	column string
}

func main() {
	output := flag.String("output", filepath.Join("..", "docs", "schema.md"), "output markdown path")
	flag.Parse()
	if err := generate(*output); err != nil {
		panic(err)
	}
}

func generate(output string) error {
	dir, err := os.MkdirTemp("", "tanabata-schema-")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(dir) }()
	databasePath := filepath.Join(dir, "catalog.sqlite")
	store, err := catalog.Open(databasePath)
	if err != nil {
		return err
	}
	if err := store.Close(); err != nil {
		return err
	}
	db, err := sql.Open("sqlite", databasePath)
	if err != nil {
		return err
	}
	defer func() { _ = db.Close() }()
	tables, err := tableNames(db)
	if err != nil {
		return err
	}
	var out strings.Builder
	out.WriteString("# Catalog Schema\n\n")
	out.WriteString("Generated by `make schema-docs`; do not edit manually.\n\n")
	out.WriteString("```mermaid\nerDiagram\n")
	for _, table := range tables {
		for _, fk := range foreignKeys(db, table) {
			fmt.Fprintf(&out, "  %s }o--|| %s : %s\\n", table, fk.table, fk.column)
		}
	}
	out.WriteString("```\n\n")
	out.WriteString("`claims.source_id` and `claim_evidence.source_id` are ADR-005 loose references to `quote_sources.source_id`; SQLite does not enforce them as foreign keys.\n\n")
	for _, table := range tables {
		fmt.Fprintf(&out, "## `%s`\n\n| Column | Type | Nullable | FK |\n| --- | --- | --- | --- |\n", table)
		fks := foreignKeys(db, table)
		fkByColumn := map[string]string{}
		for _, fk := range fks {
			fkByColumn[fk.column] = fk.table
		}
		for _, col := range columns(db, table) {
			nullable := "yes"
			if !col.nullable || col.primary {
				nullable = "no"
			}
			if col.primary {
				col.typeName += " (PK)"
			}
			fmt.Fprintf(&out, "| `%s` | `%s` | %s | %s |\n", col.name, col.typeName, nullable, fkByColumn[col.name])
		}
		out.WriteString("\n")
	}
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil { // #nosec G301 -- generated documentation is public
		return err
	}
	content := strings.TrimRight(out.String(), "\n") + "\n"
	return os.WriteFile(output, []byte(content), 0o644) // #nosec G306 -- generated documentation is public
}

func tableNames(db *sql.DB) ([]string, error) {
	rows, err := db.Query(`SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tables []string
	for rows.Next() {
		var table string
		if err := rows.Scan(&table); err != nil {
			return nil, err
		}
		tables = append(tables, table)
	}
	return tables, rows.Err()
}

func columns(db *sql.DB, table string) []column {
	rows, err := db.Query(`PRAGMA table_info(` + table + `)`)
	if err != nil {
		panic(err)
	}
	defer rows.Close()
	var values []column
	for rows.Next() {
		var index, notNull, primary int
		var value column
		var defaultValue any
		if err := rows.Scan(&index, &value.name, &value.typeName, &notNull, &defaultValue, &primary); err != nil {
			panic(err)
		}
		value.nullable = notNull == 0
		value.primary = primary != 0
		values = append(values, value)
	}
	return values
}

func foreignKeys(db *sql.DB, table string) []foreignKey {
	rows, err := db.Query(`PRAGMA foreign_key_list(` + table + `)`)
	if err != nil {
		panic(err)
	}
	defer rows.Close()
	var values []foreignKey
	for rows.Next() {
		var id, sequence int
		var value foreignKey
		var to, onUpdate, onDelete, match string
		if err := rows.Scan(&id, &sequence, &value.table, &value.column, &to, &onUpdate, &onDelete, &match); err != nil {
			panic(err)
		}
		values = append(values, value)
	}
	sort.Slice(values, func(i, j int) bool { return values[i].column < values[j].column })
	return values
}
