FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

ARG TARGETPLATFORM
RUN apk add --no-cache tini && adduser -D -u 10001 tanabata
WORKDIR /app
COPY --chown=tanabata:tanabata ${TARGETPLATFORM}/tanabata /usr/local/bin/tanabata
COPY --chown=tanabata:tanabata api/data /app/data
COPY --chown=tanabata:tanabata openapi /app/openapi

EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 CMD wget -qO- http://localhost:8080/readyz || exit 1
USER tanabata
ENTRYPOINT ["/sbin/tini", "--", "tanabata"]
