FROM alpine:3.20@sha256:d9e853e87e55526f6b2917df91a2115c36dd7c696a35be12163d44e6e2a4b6bc

ARG TARGETPLATFORM
RUN apk add --no-cache tini && adduser -D -u 10001 tanabata
WORKDIR /app
COPY --chown=tanabata:tanabata ${TARGETPLATFORM}/tanabata /usr/local/bin/tanabata
COPY --chown=tanabata:tanabata api/data /app/data
COPY --chown=tanabata:tanabata openapi /app/openapi

EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 CMD wget -qO- http://localhost:8080/readyz || exit 1
USER tanabata
ENTRYPOINT ["/sbin/tini", "--", "tanabata"]
