FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

ARG TARGETPLATFORM
RUN apk add --no-cache tini && adduser -D -u 10001 tanabata
WORKDIR /app
COPY --chown=tanabata:tanabata ${TARGETPLATFORM}/tanabata /usr/local/bin/tanabata
COPY --chown=tanabata:tanabata api/data /app/data
COPY --chown=tanabata:tanabata openapi /app/openapi

EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 CMD wget -qO- http://localhost:8080/readyz || exit 1
USER tanabata
ENTRYPOINT ["/sbin/tini", "--", "tanabata"]
