name: Monthly Scraper

on:
  schedule:
    - cron: '0 0 1 * *'  
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04  
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              libnss3 \
              libnspr4 \
              libatk1.0-0 \
              libatk-bridge2.0-0 \
              libcups2 \
              libdrm2 \
              libxkbcommon0 \
              libxcomposite1 \
              libxdamage1 \
              libxfixes3 \
              libxrandr2 \
              libgbm1 \
              libasound2 \
              libffi8 \
              libx264-164
      - name: Install Python dependencies
        working-directory: ./scraper
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
      - name: Run scraper
        working-directory: ./scraper
        run: python scraper.py
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add api/data/quotes.json
          git commit -m "Update quotes.json"
          git push