name: Monthly Scraper

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        working-directory: ./api
        run: go get github.com/PuerkitoBio/goquery github.com/gin-gonic/gin
      - name: Run scraper
        working-directory: ./api
        run: go run main.go --scrape
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add api/data/quotes.json
          git commit -m "Update quotes.json"
          git push
