name: Monthly Scraper

on:
  schedule:
    - cron: '0 0 1 * *'  
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/api  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go get github.com/PuerkitoBio/goquery github.com/lib/pq
      - name: Build scraper
        run: go build -o scraper .
      - name: Run scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./scraper